AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'spec/factories/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
  NewCops:                                 disable
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled:                                 true
Layout/LineLength:
  Enabled:                                 false
Layout/MultilineBlockLayout:
  Enabled:                                 false
Layout/SpaceAroundMethodCallOperator:
  Enabled:                                 true
Layout/SpaceBeforeBrackets:
  Enabled:                                 true
Lint/AmbiguousAssignment:
  Enabled:                                 true
Lint/AmbiguousBlockAssociation:
   Enabled:                                false
Lint/DeprecatedOpenSSLConstant:
  Enabled:                                 true
Lint/DuplicateBranch:
  Enabled:                                 true
Lint/DuplicateElsifCondition:
  Enabled:                                 true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled:                                 true
Lint/EmptyBlock:
  Enabled:                                 true
Lint/EmptyClass:
  Enabled:                                 true
Lint/MissingSuper:
  Enabled:                                 false
Lint/MixedRegexpCaptureTypes:
  Enabled:                                 true
Lint/NoReturnInBeginEndBlocks:
  Enabled:                                 true
Lint/RaiseException:
  Enabled:                                 true
Lint/StructNewOverride:
  Enabled:                                 true
Lint/ToEnumArguments:
  Enabled:                                 true
Lint/UnexpectedBlockArity:
  Enabled:                                 true
Lint/UnmodifiedReduceAccumulator:
  Enabled:                                 true
Metrics/AbcSize:
  Max:                                     30
Metrics/BlockLength:
  Enabled:                                 true
  Exclude:
    - spec/**/*
    - lib/tasks/**/*
Metrics/ClassLength:
  Max:                                     300
Metrics/CyclomaticComplexity:
  Max:                                     8
Metrics/MethodLength:
  Max:                                     25
Metrics/PerceivedComplexity:
  Max:                                     8
Naming/RescuedExceptionsVariableName:
  Enabled:                                 false
Style/AccessorGrouping:
  Enabled:                                 true
Style/ArrayCoercion:
  Enabled:                                 true
Style/ArgumentsForwarding:
  Enabled:                                 true
Style/BisectedAttrAccessor:
  Enabled:                                 true
Style/BlockDelimiters:
  Enabled:                                 false
Style/CaseLikeIf:
  Enabled:                                 true
Style/ClassAndModuleChildren:
  Enabled:                                 false
Style/CollectionCompact:
  Enabled:                                 true
Style/DocumentDynamicEvalDefinition:
  Enabled:                                 true
Style/Documentation:
  Enabled:                                 false
Style/ExponentialNotation:
  Enabled:                                 true
Style/HashAsLastArrayItem:
  Enabled:                                 true
Style/HashEachMethods:
  Enabled:                                 true
Style/HashExcept:
  Enabled:                                 true
Style/HashLikeCase:
  Enabled:                                 true
Style/HashSyntax:
  Enabled:                                 false
Style/HashTransformKeys:
  Enabled:                                 true
Style/HashTransformValues:
  Enabled:                                 true
Style/NegatedIfElseCondition:
  Enabled:                                 true
Style/NilLambda:
  Enabled:                                 true
Style/OptionalBooleanParameter:
  Enabled:                                 false
Style/RedundantArgument:
  Enabled:                                 true
Style/RedundantAssignment:
  Enabled:                                 true
Style/RedundantFetchBlock:
  Enabled:                                 true
Style/RedundantFileExtensionInRequire:
  Enabled:                                 true
Style/RedundantRegexpCharacterClass:
  Enabled:                                 true
Style/RedundantRegexpEscape:
  Enabled:                                 true
Style/RegexpLiteral:
  Enabled:                                 false
Style/SlicingWithRange:
  Enabled:                                 true
Style/SwapValues:
  Enabled:                                 true
