development:
  adapter:        async

test:
  adapter:        test

production:
  adapter:        redis
  url:            <%= Rails.application.credentials.redis.url { "redis://localhost:6379/1" } %>
  channel_prefix: brick_city_production
