# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

# Add product types
instructions = ProductType.find_or_create_by(name: 'Instructions', digital_product: true, ready_for_public: true, comes_with_title: 'What do I get when I buy instructions?', description: 'Instructions include a PDF with clear steps on how to build the models. They also include an HTML parts list you can open in your internet browser. This parts list includes a checklist you can use to determine how many of each piece you already have. Submit your checklist, and customized XML is generated that you can use to upload to your Bricklink Wanted List to acquire the pieces you still need. Check out our FAQ and BCD Tutorial if you have any questions.', comes_with_description: 'You get a PDF with complete picture instructions using easy to follow steps. You also get 2 parts lists you can use to collect the pieces necessary to complete our models. We give complete instructions on how to use the parts lists on our new user tutorial page here: www.brickcitydepot.com/new_user_tutorial')
models = ProductType.find_or_create_by(name: 'Models', digital_product: false, ready_for_public: true, comes_with_title: 'What do I get when I buy a model?', description: "Models are based off of our existing products and might not conform to our instructions. Building interiors, bricks used, parts counts and colors may vary from what you see in the instructions for the model. Models come with downloadable instructions for the related item, although the instructions may not match up with the model you are getting. Instructions will always show you how to build the 'official' model. We only use new parts for our models, unless new ones aren't available. If you're interested in the building experience, check out our kits.", comes_with_description: 'You may or may not get a PDF with complete picture instructions and parts lists depending on if the model is one you can also buy instructions for. If you can buy the instructions separately, then they will be included with this model. Kits will include all necessary pieces to build the model. Pre-built models may or may not conform exactly to the instructions you get for the model.')
kits = ProductType.find_or_create_by(name: 'Kits', digital_product: false, ready_for_public: true, comes_with_title: 'What do I get when I buy a kit?', description: "Kits include complete downloadable instructions and parts lists along with all the pieces needed to build the model. After your purchase is completed, you will be able to download instructions and we will ship the pieces for the model to you via the address you have registered with Paypal. If you just want to expand your city and don't have time to build a kit, check out our models.", comes_with_description: 'You get a PDF with complete picture instructions using easy to follow steps. You also get 2 parts lists you can use to collect the pieces necessary to build the model. Kits will also include all necessary pieces to build the model. Pre-built models may or may not conform to the instructions you get for the model.')
crafts = ProductType.find_or_create_by(name: 'Crafts', digital_product: false, ready_for_public: false, comes_with_title: '', description: '', comes_with_description: '')

# Add categories
city_category = Category.find_or_create_by(name: 'City', description: "Build your city or town up with these great models that will fit right in with your existing setup. Modular buildings in the Cafe Corner style, smaller playset-type buildings, cars and trucks to get your Lego people where they're going. Bring your city to life.", ready_for_public: true)
train_category = Category.find_or_create_by(name: 'Train', description: 'Expand your layout with these awesome rail models. Buildings, engines, rolling stock, passenger cars, maintenance of way vehicles, past, present, everything you need to make your layout first class.', ready_for_public: true)
military_category = Category.find_or_create_by(name: 'Military', description: "Have fun building military vehicles and buildings from the past and present. Re-live some of history's great battles with these excellent models.", ready_for_public: true)
winter_village_category = Category.find_or_create_by(name: 'Winter Village', ready_for_public: true, description: 'Expand your Winter Village with these great models from Brick City Depot. All models have open backs for a playset feel.')
# castle_category = Category.create(:name => "Castle", :ready_for_public => true, :description => "Bring your castle layout to life with these great add-ons. Whether you are building peasant villages, or pitched battles for control of a castle, Brick City Depot has you covered.")
retired_category = Category.find_or_create_by(name: 'Retired', ready_for_public: false, description: 'This category is for retired models. A retired model is one that has at least 1 order. Otherwise we could just delete the product. This will let us be able to see historical numbers, even for products no longer available to the public.')
other_category = Category.find_or_create_by(name: 'Other', ready_for_public: true, description: "Everything that doesn't quite fit into the other categories; castle, fantasy, technic, mini, micro, etc.")
alternative_category = Category.find_or_create_by(name: 'Alternative Builds', ready_for_public: false, description: 'These models use pieces mostly from a single official Lego set, making pieces much easier to acquire. All you have to do is buy the specified Lego set, and perhaps a few additional pieces to complete the set.')

# Add Subcategories
city_vehicles = Subcategory.find_or_create_by(name: 'Vehicles', category_id: city_category.id, code: 'CV', ready_for_public: true)
city_buildings = Subcategory.find_or_create_by(name: 'Modular Buildings', category_id: city_category.id, code: 'CB', ready_for_public: true)
train_buildings = Subcategory.find_or_create_by(name: 'Buildings', category_id: train_category.id, code: 'TB', ready_for_public: true)
train_engines = Subcategory.find_or_create_by(name: 'Engines and Rolling Stock', category_id: train_category.id, code: 'TE', ready_for_public: true)
world_war2 = Subcategory.find_or_create_by(name: 'World War II', category_id: military_category.id, code: 'WW', ready_for_public: true)
modern_warfare = Subcategory.find_or_create_by(name: 'Modern Warfare', category_id: military_category.id, code: 'MW', ready_for_public: true)
castle = Subcategory.find_or_create_by(name: 'Castle', category_id: other_category.id, code: 'CA', ready_for_public: true)
mini_micro = Subcategory.find_or_create_by(name: 'Mini & Micro', category_id: other_category.id, code: 'MM', ready_for_public: true)
winter_village_buildings = Subcategory.find_or_create_by(name: 'Buildings', category_id: winter_village_category.id, code: 'WV', ready_for_public: true)
retired_subcategory = Subcategory.find_or_create_by(name: 'Retired', category_id: retired_category.id, code: 'RT', ready_for_public: false)

# Add Products
# City Vehicles
cv001 = Product.create(product_type_id: instructions.id, name: 'Rollback Tow Truck', category_id: city_category.id, subcategory_id: city_vehicles.id, product_code: 'CV001', description: 'The model that started it all. The original, the classic, the rollback tow truck. This model features a tilting and sliding bed, tool storage, and an array of levers. Vehicles that are 4 studs wide can fit on the bed with no problems. 6 stud wide cars can fit too if the bed rail system is changed.', price: 3, ready_for_public: false, tweet: 'With tilting/sliding bed and tool storage, this tow truck will fit perfectly in your Lego town.')
cv002 = Product.create(product_type_id: instructions.id, name: 'Glass Truck', category_id: city_category.id, subcategory_id: city_vehicles.id, product_code: 'CV002', price: 3, ready_for_public: false, tweet: 'This glass delivery truck will get the panes to the job on time.', description: 'Glass is going to break in your city, and who will be around to replace it when it does? Your friendly local glass replacement technicians! Get them there in this truck specially equipped to carry glass safely to the job site.')
cv003 = Product.create(product_type_id: instructions.id, name: 'Sewer Truck', category_id: city_category.id, subcategory_id: city_vehicles.id, product_code: 'CV003', price: 3, ready_for_public: false, tweet: "Clean up your city's sewers with this truck equipped for the job", description: "It's a messy job, but someone has to do it. Keep the sewers clean and functioning properly in your city for the public's health and safety. Watch for alligators! Truck has a hose that can reach from the back of the truck to a manhole.")
cv004 = Product.create(product_type_id: instructions.id, name: 'Hi Rail Pickup', category_id: city_category.id, subcategory_id: city_vehicles.id, product_code: 'CV004', price: 3, ready_for_public: false, tweet: 'Make sure the rails are clear and safe with this rail maintenance pickup', description: "You can't just trust that the rails in your layout will be clear and free of damage. You need someone to go inspect before the passenger trains come through. This maintenance of way pickup is perfect for riding the rails ahead of the trains and ensuring the safety of the trains to come. Instructions include steps to build both single and double plows.")
cv005 = Product.create(product_type_id: instructions.id, name: 'NYPD Emergency Support Vehicle', category_id: city_category.id, subcategory_id: city_vehicles.id, product_code: 'CV005', price: 3, ready_for_public: false, tweet: 'Launch the raft and get to the foundering ship quickly with this boat-launching truck.', description: "When there's a boat in trouble, you need first responders to get to the scene quickly. This New York Police Department truck is equipped to launch a raft and get officers to the rescue of distressed boaters quickly. Truck has removable side panels for equipment storage.")
cv006 = Product.create(product_type_id: instructions.id, name: 'NYPD Radio Truck', category_id: city_category.id, subcategory_id: city_vehicles.id, product_code: 'CV006', price: 3, ready_for_public: false, tweet: "NYPD's elite emergency services unit's radio truck.", description: "New York Police Departments' elite Emergency Services Unit is a combined rescue/SWAT team that are called on when situations get out of hand. This is their radio truck.")
cv007 = Product.create(product_type_id: instructions.id, name: 'Hi Rail Dump Truck', category_id: city_category.id, subcategory_id: city_vehicles.id, product_code: 'CV007', price: 3, ready_for_public: false, tweet: 'Time for rail repair! Get the job done with this Hi Rail Dump Truck.', description: "When it's time to repair your rails, send in the heavy equipment to get the job done. This maintenance of way dump truck can haul rocks to repair a washed-out rail bed. Dumper bed tilts and the rear door opens to dump the load. Instructions come with steps for building single and double plows.")
cv008 = Product.create(product_type_id: instructions.id, name: 'Fire Brush Truck', category_id: city_category.id, subcategory_id: city_vehicles.id, product_code: 'CV008', price: 3, ready_for_public: false, tweet: 'Get deep into the woods to fight fires with this rough and ready brush truck.', description: 'Your rural fire crew needs a truck like this one to get back into the woods and get to where the action is when the forest fires are raging out of control. Heavy-duty brush guard protects the front end of the truck when getting into deep underbrush. Lift up the rear tailgate to get access to hose storage and the trucks controls.')
cv009 = Product.create(product_type_id: instructions.id, name: 'Work Truck', category_id: city_category.id, subcategory_id: city_vehicles.id, product_code: 'CV009', price: 3, ready_for_public: false, tweet: 'This generic work truck features some great SNOT techniques.', description: 'This generic work truck can serve many purposes in your city. Truck can be used as an electricians truck, plumbers truck, cable installers truck, etc. Customize it by adding stickers for your favorite company, or adding ladders on top. The truck cab is 6 studs wide, and the body is 7 studs wide. The truck body incorporates 7 cabinets for tool/hardware storage, and makes heavy use of SNOT techniques to fit so much storage in such a small space.')
cv010 = Product.create(product_type_id: instructions.id, name: 'American Ambulance', category_id: city_category.id, subcategory_id: city_vehicles.id, product_code: 'CV010', price: 3, ready_for_public: false, tweet: 'Get to the scene of the accident quickly with this Lego ambulance.', description: "Help keep your city's residents safe and make sure they have quick transport to the hospital should there be an accident. This ambulance features a removable roof and opening rear doors for accessing the rear. The patient area has an IV tower, lifesaving station, and a place to keep a stretcher secure. Ambulance also features a detailed undercarriage.")
cv011 = Product.create(product_type_id: instructions.id, name: 'Hot Rod', category_id: city_category.id, subcategory_id: city_vehicles.id, product_code: 'CV011', description: "Let your minifigs cruise the streets in style with this model patterned after a '32 Ford Hot Rod.  These instructions include variations for both coupe and convertible. This model can be built in either red or black.", price: 2.5, tweet: "Cruise the Lego streets in style with this sweet '32 Ford Hot Rod", ready_for_public: false)
cv012 = Product.create(product_type_id: instructions.id, name: 'Vintage Police Car', category_id: city_category.id, subcategory_id: city_vehicles.id, product_code: 'CV012', price: 2, ready_for_public: false, tweet: 'Patrol the streets and keep your city safe with this vintage cruiser.', description: 'Keep your citizens safe by patrolling the mean streets in this vintage cruiser. This model is patterned after older style black and whites. Model features a simple build, classic vehicle sizing and a spotlight on the drivers side.')
cv013 = Product.create(product_type_id: instructions.id, name: 'Adventure Truck', category_id: city_category.id, subcategory_id: city_vehicles.id, product_code: 'CV013', price: 2, ready_for_public: false, description: "This sweet ride would be the perfect truck to get your minifigs to a back-country adventure. There's a winch up front behind the big bumper to get them out of sticky situations, a spare tire mounted on the back, a jerry can with extra gas, off-road lights, and a roof rack for carrying adventure equipment. This truck has it all!")

# City Buildings
cb001 = Product.create(product_type_id: instructions.id, name: 'Police Precinct', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB001', price: 10, ready_for_public: false, tweet: 'This police precinct will fit in with your existing modular buildings.', description: "Your modular city police need a downtown headquarters in order to keep tabs on the criminal element that prey on innocent civilians. This building is modular and features a furnished interior. First floor has a receiving desk, weapons rack and desks for detectives. Second floor has a lineup room, interrogation room and a holding cell. Instructions include directions for building the CV012 Vintage Police Car. There are also directions for building a bat-signal to go on the roof, if that's your sort of thing. Building sits on a 32x32 baseplate.")
cb002 = Product.create(product_type_id: instructions.id, name: 'Colonial Revival House', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB002', description: 'One of our best sellers, the Colonial Revival house modeled after a real house in the Fan in Richmond, VA. This model is modular and features 2 furnished floors, a crawlspace and a porch on front and back. This model will go great in any row house neighborhood in your modular city. Building sits on a 16x32 baseplate.', price: 10, ready_for_public: false, tweet: 'Classic row house architecture to jump-start your modular neighborhood.')
cb003 = Product.create(product_type_id: instructions.id, name: 'Stone-Faced Restaurant', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB003', price: 10, ready_for_public: false, tweet: 'Customize this restaurant for your modular city.', description: "Your modular city citizens want to have somewhere nice to eat out when they feel like a night out on the town. You can choose what type of restaurant you'd like to add to your city using 1 of the 4 logos we give you directions to build. Choose from a cheeseburger, noodle bowl, soup bowl or martini glass logo, or create your own logo! Model features a modular build, and a detailed interior with a spacious dining area and a full kitchen. Building sits on a 32x32 baseplate.")
cb004 = Product.create(product_type_id: instructions.id, name: 'Vintage Service Station', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB004', price: 7.5, ready_for_public: false, tweet: 'Bring your car to this classic service station where the customer is still # 1.', description: "A classic service station to service your classic cars. Customer service isn't a thing of the past at this station modeled after vintage Texaco service stations. This model features a vintage Coke machine, a single bay for working on cars, old-style pumps, and a convertible based on cars from the 1950s. Building sits on a 16x32 baseplate.")
cb005 = Product.create(product_type_id: instructions.id, name: 'Upper West Side Brownstone House', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB005', price: 12, ready_for_public: false, tweet: 'Check out this classic New York City architecture.', description: "This classic Brownstone features 3 fully furnished floors, a complete fire escape, stairs between floors, details in and out, and great looks. Your modular city citizens will be proud to live in this high-end residence and show to everyone that they've 'made it'. Building sits on a custom-sized baseplate area of 24x32 studs.")
cb006 = Product.create(product_type_id: instructions.id, name: 'City Residential Pack 1', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB006', price: 1, ready_for_public: false, description: 'Your minifigs need a place to live, and what better place than this cozy set of houses? These 2 houses were modeled after real houses in the Fan District in Richmond, VA. Check out the front porches where neighbors can get together after work and chat. The City Residential series does not include instructions for detailed interiors.')
cb007 = Product.create(product_type_id: instructions.id, name: 'City Residential Pack 2', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB007', price: 1, ready_for_public: false, description: 'Check out these beauties! These houses are based on 2 real houses in the Fan District in Richmond, VA. The roof sections include some intricate details and feature advanced building techniques. Details are sprinkled throughout, like the small birdhouse out front, the martin house out back, the green house, the fenced alleyway, and the vine growing from the ground up to the top of the 2nd floor. The City Residential series does not include instructions for detailed interiors.')
cb008 = Product.create(product_type_id: instructions.id, name: 'Commercial Pack 1', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB008', price: 1, ready_for_public: false, description: 'These 2 buildings look like they belong in an older part of town that has maybe seen better days. The dark green/brown building is a pub/bar and features a pinball machine, pool table and cue racks. The dark gray/black building is a generic store. Both feature detail in the rear of the building that helps sell the rundown look.')
cb009 = Product.create(product_type_id: instructions.id, name: 'National Bank', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB009', price: 1, ready_for_public: false, description: 'This neoclassical styled bank is based on the First National Bank building in downtown Richmond, VA. This one will really stand out in your modular city. The first floor has a teller window and a few desks. The second floor has a vault or a security box room, and a loan office. The third floor is an office area where the employees are hard at work.')
cb010 = Product.create(product_type_id: instructions.id, name: 'Brick City Bakery', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB010', price: 1, ready_for_public: false, description: 'Your minifigs need sweets, right? Come down to the Brick City Bakery for all your cookies, cakes, pies and pastries. Have a party that needs to be catered? Brick City Bakery has a delivery truck that has racks for holding several pastry trays, and can bring the goods to you. The first floor is the bakery and the second floor is the bakery owners apartment.')
cb011 = Product.create(product_type_id: instructions.id, name: "Chili's Restaurant", category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB011', price: 1, ready_for_public: false, description: "This Chili's restaurant is based on some real Chili's. You may have even driven by one that looks like this in your town. Your minifigs will enjoy eating out at the best chain Tex-Mex restaurant around. Inside has a full kitchen, guys and gals bathrooms, booths to seat 16, and a bar. The exterior is one of our best and features great details up front, out back and on the roof. This one will be a highlight of your modular city.")
cb012 = Product.create(product_type_id: instructions.id, name: 'Corner Shop and Apartments', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB012', price: 1, ready_for_public: false, description: "This beautiful Neo-Dutch Renaissance building is the first in our Amsterdam series. It's based off a jewelry store in the heart of Amsterdam on Muntplein Square. It has 3 floors and a full interior. The first floor is a jewelry store which can be accessed from the door on the right. The 2nd and 3rd floors are detailed apartments that can be accessed through the door on the left.")
cb013 = Product.create(product_type_id: instructions.id, name: 'Canal Street Houses', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB013', price: 1, ready_for_public: false, description: "This is the 2nd model in our Amsterdam series. They are based off of houses you'll typical find on the streets lining the canals. The blue house features an office downstairs with a detailed bathroom. The 2nd floor has an eat-in kitchen featuring a toaster, food processor and dishwasher and a living area. Up to the 3rd floor, where there is a bedroom and bathroom that features a glass-bowl sink, shower stall and a towel rack. The brown building is a bit skinnier and has a kitchen and sitting area on the first floor. The 2nd floor has a bedroom and computer desk and the 3rd floor has a drafters office.")
cb014 = Product.create(product_type_id: instructions.id, name: 'Consulate', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB014', price: 1, ready_for_public: false, description: "This model can be built using about half the pieces from 10224 Town Hall. The only things you will need to add are 2 stair pieces. The first floor is the main lobby with a receptionist desk and a waiting area. The 2nd floor is a break room for the employees. The 3rd floor has an office and secretary's desk. Outside is a parking lot with a guard shack and a couple of security cameras watching the parking lot. The high walls and fence on top of the walls should keep out intruders. On the roof is a satellite dish for a secure communications channel.")
cb015 = Product.create(product_type_id: instructions.id, name: 'Amsterdam Hotel', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB015', price: 1, ready_for_public: false, description: 'This is the 3rd model in our Amsterdam series and was modeled after one end of the Amstel Hotel in Amsterdam. This hotel features French Renaissance architecture. The first floor is a lobby with a front desk, stairs, a fountain, chairs, and a bathroom. The second floor has stairs and a door to a patio. The third level has 2 rooms for the guests. This is one of our best models and attracts a lot of attention wherever we display it.')
cb016 = Product.create(product_type_id: instructions.id, name: 'Amsterdam Gift Shop', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB016', price: 1, ready_for_public: false, description: "This building is the 4th in our Amsterdam series. It features a gift shop on the first floor. The 2nd through 4th floor are the gift shop owner's apartment. There's a kitchen and dining area on the 2nd floor, living area with a nautical theme on the 3rd floor, and bedroom and bathroom on the 4th floor. The building was due for a bit of a facelift, so some painters came and set up a (very stable) scaffold out front so they could work on the upper floors.")
cb017 = Product.create(product_type_id: instructions.id, name: 'San Francisco Victorian House', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB017', price: 1, ready_for_public: false, description: 'This Victorian house is the first in our San Francisco series. It was modeled after several houses in SF. It has a garage with working door, and a workshop on the lower level. There is a kitchen and a foyer on the middle floor and upstairs there is a bedroom and bathroom.')
cb018 = Product.create(product_type_id: instructions.id, name: 'San Francisco Stick Style House', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB018', price: 1, ready_for_public: false, description: 'This beautiful Victorian house is the 2nd in our San Francisco series. It was modeled after a real house in San Francisco built with stick style architecture. The basement or garage is a music room, the middle level is a kitchen and sitting area and upstairs is the bedroom. This house looks beautiful next to the Colonial Revival and San Francisco Victorian houses. Your minifigs will be living in style in this house.')
cb019 = Product.create(product_type_id: instructions.id, name: 'City Residential Pack 3', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB019', price: 1, ready_for_public: false, description: "This is the 3rd in our City Residential series. This pair of London Row Houses are modeled after a real pair of houses in Notting Hill. These houses feature courtyards up front, and some bold colors. If red and blue aren't your thing, you can easily switch the red and blue bricks for a color more to your liking. The City Residential series does not include instructions for detailed interiors.")
cb020 = Product.create(product_type_id: instructions.id, name: 'City Townhouse', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB020', price: 1, ready_for_public: false, description: "This model is an alternative to 10197 Fire Brigade. If you bought a 2nd Fire Brigade, use the pieces to build this little contemporary-styled townhouse. Even if you didn't buy 2 Fire Brigades, the pieces for this model will be easy to come by. You will need about half the pieces of the original model to build the townhouse and the alternative fire truck that's included. The first floor is a garage, the 2nd floor is a kitchen with seating area, and the 3rd floor is a bedroom.")
cb021 = Product.create(product_type_id: instructions.id, name: 'Mansard Row House', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB021', price: 1, ready_for_public: false, description: 'This great little alternative model uses the pieces of 10228 Haunted House, plus 30 common pieces. These 30 pieces were necessary to make the model fit in with other modulars adhering to the Cafe Corner standard. This house does not include instructions for a detailed interior.')
cb022 = Product.create(product_type_id: instructions.id, name: 'City Residential Pack 4', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB022', price: 1, ready_for_public: false, description: 'This is the 4th in the City Residential series. The sand blue house is based off of a real house in Georgetown, Washington, DC. It features a sloping garden up front and architectural styling typical for the area. The dark green house features ornate window casements and a detailed entryway. The City Residential series does not include instructions for a detailed interior. They do both have stairs built in, and the blue house has walls for different rooms upstairs.')
cb023 = Product.create(product_type_id: instructions.id, name: 'Hardware Store', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB023', price: 1, ready_for_public: false, description: 'This classic corner hardware store brings back the styling and architecture of the early 20th century. The first floor features a hardware store with a backroom that has an unloading dock that the truck can back up to and drop off its goods. The 2nd story apartment is accessed by the stairs out front. It has a den, kitchen, bedroom and bathroom.')
cb024 = Product.create(product_type_id: instructions.id, name: 'Four Stars Comedy Club', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB024', price: 1, ready_for_public: false, description: 'This 10232 Palace Cinema alternative is a comedy club which would look great in your city layout. The only piece you need to add is the base plate. The first floor features a stage with audience seating. The second floor has a lounge so your minifigs can hang out and relax.')
cb025 = Product.create(product_type_id: instructions.id, name: 'Town Shop', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB025', price: 1, ready_for_public: false, description: 'This Town Shop is a 10211 Grand Emporium alternative model. You will just need to add the baseplate. The first floor features a shop with some knick knacks on the shelves. The 2nd floor is open for you to add whatever you want.')
cb026 = Product.create(product_type_id: instructions.id, name: 'Smokestacks Coffee House', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB026', price: 1, ready_for_public: false, description: "The Smokestacks Coffee House is a renovated factory that now serves a dual purpose. On the first floor there is a coffee shop with a covered outdoor patio, community board, and attention-grabbing giant coffee cup. On the 2nd floor there is a tech startup company, with a kitchenette, bike rack, cluster of desks, water cooler and server racks. The old factory skylights bring natural light to the building's newest workers. Urban renewal at it's finest!")
cb027 = Product.create(product_type_id: instructions.id, name: 'Menswear Shop', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB027', price: 1, ready_for_public: false, description: 'This corner store is a menswear shop packed inside and out with details that make this an awesome building experience. There are 2 floors of merchandise while the third floor has an office and the inventory. This building is modeled after a real retail location in downtown Washington DC. On the roof are 2 large AC units and some solar panels to appease the greenies. Check out all the details, like the security cameras, dressing rooms, coat racks, managers office, parking meters and traffic lights with crosswalk lights.')
cb028 = Product.create(product_type_id: instructions.id, name: 'Architecture Firm', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB028', price: 1, ready_for_public: false, description: "This building was designed by an architecture firm as their home office to showcase their talents. The open lobby on the first floor has a waiting area with a living wall, receptionist desk, and scale models of buildings the architects have designed, including a scale model of the architecture firm itself. Take the glass elevator to the second floor where there's a bathroom and office. The third floor has another office and a conference room. Back on the elevator to the 4th floor, up to the break room. Step outside to the rooftop patio, where your minifigs can recharge their batteries at the outdoor tables. They can relax amongst the greenery, and enjoy a commanding view of the city. In a city full of old buildings, this example of modern architecture will stand apart.")
cb029 = Product.create(product_type_id: instructions.id, name: 'Speakeasy', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB029', price: 1, ready_for_public: false, description: 'Club 23 Speakeasy is straight out of the prohibition days of the 1920s which is why there is a Model A included as well. Up front there is a very small shop to provide cover for what is behind. The speakeasy is accessed through the phone booth. Your minifigs will be treated to a small casino and bar in the back room. There is a roulette table, craps table, piano and a bar. If the police arrive the top of the gaming tables can be covered up, the roulette wheel can be flipped over on to cover the top of the barrel where all the drinks are thrown. Upstairs there is a small brewery and an office for the gangster that controls the whole operation.')
cb030 = Product.create(product_type_id: instructions.id, name: 'Commercial Pack 2', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB030', price: 1, ready_for_public: false, description: 'These 2 buildings would look great on your commercial strip. The Japanese restaurant has 2 tables in the eating area, a large aquarium, some decorative art on the walls, and a curved Japanese-style roof. The board shop features an attention-grabbing sign on the front, a sunglasses rack and interior displays for all the types of boards. Out back there is a ladder to get up to the roof, where the employees like to grill out and chill after a long day at work. This modular features some tricks for creating odd-width buildings. Normally, our buildings are 16 studs wide or 32 studs wide. The Japanese restaurant is 17 studs wide, and the Board Shop is 15 studs wide, and go together on a 32 stud wide baseplate. This is a fun build and goes great with your modular town.')
cb031 = Product.create(product_type_id: instructions.id, name: 'Commercial Facade Pack', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB031', price: 1, ready_for_public: false, description: 'This is a 4 n 1 instruction pack. After building the base model there are 4 different instructions for different facades that you can add to the front. This was an idea that we created and implemented in our first book. There are different parts list for each facade so you can choose which ones you want to build. Have fun experimenting to see what other facades you can add to the front.')
cb032 = Product.create(product_type_id: instructions.id, name: 'European Hotel', category_id: city_category.id, subcategory_id: city_buildings.id, product_code: 'CB032', price: 1, ready_for_public: false, description: 'This European Hotel features some stunning architecture and details inside and out. This was first featured in "The Lego Neighborhood Book 2". This is the first of several instructions that will be released from models that were showcased in our 2nd book.')

# Winter Village
wv001 = Product.create(product_type_id: instructions.id, name: 'Winter Village Train Station', category_id: winter_village_category.id, subcategory_id: winter_village_buildings.id, product_code: 'WV001', price: 5, ready_for_public: false, tweet: 'Add to your winter village and train layouts at the same time', description: 'This little train station is just the right size to go along with the winter village series. You can use this model to expand both your winter village layout and your train layout. These instructions also include directions to make some rail accessories, such as an old-time mailcatcher.')
wv002 = Product.create(product_type_id: instructions.id, name: 'Winter Village Victorian House', category_id: winter_village_category.id, subcategory_id: winter_village_buildings.id, product_code: 'WV002', price: 5, ready_for_public: false, tweet: "This model will bring back memories of Christmas trips to Grandma's house.", description: "The second in Brick City Depot's winter village series, this house was designed to evoke memories of Christmas trips to Grandma's house. The house is built in a Victorian style, and has an open back consistent with the winter village series.")
wv003 = Product.create(product_type_id: instructions.id, name: 'Winter Village Gas Station', category_id: winter_village_category.id, subcategory_id: winter_village_buildings.id, product_code: 'WV003', price: 5, ready_for_public: false, tweet: 'This little gas station has a tow truck for rescuing stranded holiday travelers.', description: "The third model in Brick City Depot's winter village series, this little gas station is just the thing to complement your existing winter village. The gas station features a nice little technique for adding 'snow' to any roof, a vintage-styled pump and directions to build a tow truck. Remove the holiday dressing and the snow, and this small gas station would fit in with any small town layout.")
wv004 = Product.create(product_type_id: instructions.id, name: 'Winter Village Fire Station', category_id: winter_village_category.id, subcategory_id: winter_village_buildings.id, product_code: 'WV004', price: 10, ready_for_public: false, tweet: 'Keep your winter village citizens safe with this great fire station.', description: "This winter village fire station features a removable roof, open back consistent with the winter village series, bunk room for your firefighters, and a nice technique for adding 'snow' to any roof. Also includes directions for building a vintage-styled open cab fire truck. This building has a nice playset feel to it.")

# Train Engines/Rolling Stock
te001 = Product.create(product_type_id: instructions.id, name: 'Norfolk Southern Passenger Cars', category_id: train_category.id, subcategory_id: train_engines.id, product_code: 'TE001', price: 7.5, ready_for_public: false, tweet: 'Classic coach styling from the golden age of railroading.', description: 'These passenger coaches are modeled after vintage Norfolk Southern cars. Instructions include directions to build four different cars; business car, passenger car, dining car and observation car. All four have removable roofs for easy access to the interior.')
te002 = Product.create(product_type_id: instructions.id, name: 'Black Boxcar', category_id: train_category.id, subcategory_id: train_engines.id, product_code: 'TE002', price: 3, ready_for_public: false, tweet: 'Add to your cargo train with this generic boxcar.', description: 'Build this boxcar in several different colors and fill out your railyard. An easy build that lends itself to repeating several times in order to build up your train collection. Model features sliding doors on both sides.')
te003 = Product.create(product_type_id: instructions.id, name: 'Diesel Switcher and Refrigerator Car', category_id: train_category.id, subcategory_id: train_engines.id, product_code: 'TE003', price: 1, ready_for_public: false, description: 'This diesel switcher can be built with or without Power Functions. The instructions show how to include Power Functions to drive the train and provide lights. The switcher is based off the GM SW1. The refrigerator car is based off of modern refrigerator car design.')

# Train Buildings
tb001 = Product.create(product_type_id: instructions.id, name: 'Signal Box', category_id: train_category.id, subcategory_id: train_buildings.id, product_code: 'TB001', price: 5, ready_for_public: false, tweet: 'Classic rail architecture built in a modular style', description: 'This signal box is built in a modular style, with separate first floor, second floor and roof sections. This model features nice little details such as a power meter box, a control board on the second floor and tool storage on the first floor. The second story has windows all around so your crew will have a 360 degree view of the railyard. Building sits on a 16x32 baseplate.')
tb002 = Product.create(product_type_id: instructions.id, name: 'Small Town Train Station', category_id: train_category.id, subcategory_id: train_buildings.id, product_code: 'TB002', price: 10, ready_for_public: false, tweet: '', description: 'This small train station evokes classic small town train stations. With just a few parking spots, a single ticket booth and a small platform, this station is just the right size for a stop in your small town. Directions are given on how to place the track to accommodate 6,7 and 8-stud wide trains. Building and parking lot sit on a custom-sized 32x56 baseplate area.')

# Military
ww001 = Product.create(product_type_id: instructions.id, name: 'Higgins Boat LCVP', category_id: military_category.id, subcategory_id: world_war2.id, product_code: 'WW001', price: 5, ready_for_public: false, tweet: 'Storm the beaches with this historical landing craft.', description: "The Higgins Boat, or LCVP, is an iconic piece of World War II hardware. More than 20,000 were built with the express purpose of landing soldiers on foreign soil to establish a beachhead for an invasion. This craft most famously served this purpose on June 6th, 1944 when the Allies launched the largest invasion the world had ever seen to try and penetrate Hitler's Atlantic wall. Read more about this historic watercraft at http://en.wikipedia.org/wiki/LCVP")
ww002 = Product.create(product_type_id: instructions.id, name: 'Bombed Out French Building', category_id: military_category.id, subcategory_id: world_war2.id, product_code: 'WW002', price: 5, ready_for_public: false, tweet: 'This shattered building speaks to the destruction of war.', description: 'This building features a lot of techniques meant to make a building look damaged. Details include lots of little bits of damage, including hanging sections of floor and roof, and portions of the building strewn about. The second story has a perfect place for a machine gun nest to overlook the intersection below.')
ww003 = Product.create(product_type_id: instructions.id, name: 'WWII Ruined House', category_id: military_category.id, subcategory_id: world_war2.id, product_code: 'WW003', price: 1, ready_for_public: false, description: "This bombed out French house would look great with your WWII minifigs and vehicles. It's a perfect match with WW004 Ruined Barn and WW005 Ruined Factory. Build all 3 to get your war-torn town started.")
ww004 = Product.create(product_type_id: instructions.id, name: 'WWII Ruined Barn', category_id: military_category.id, subcategory_id: world_war2.id, product_code: 'WW004', price: 1, ready_for_public: false, description: "This bombed out barn would look great with your WWII minifigs and vehicles. It's a perfect match with WW003 Ruined House and WW005 Ruined Factory. Build all 3 to get your war-torn town started.")
ww005 = Product.create(product_type_id: instructions.id, name: 'WWII Ruined Factory', category_id: military_category.id, subcategory_id: world_war2.id, product_code: 'WW005', price: 1, ready_for_public: false, description: "This winter time bombed out building would look great with your WWII minifigs and vehicles. It's a perfect match with WW003 Ruined House and WW004 Ruined Barn. Build all 3 to get your war-torn town started.")
ww006 = Product.create(product_type_id: instructions.id, name: 'WWII Folding French House', category_id: military_category.id, subcategory_id: world_war2.id, product_code: 'WW006', price: 1, ready_for_public: false, description: 'This French house has seen some action. It has a crumbling exterior, sunken-in section of roof and a crack in the wall. It features a full interior with bedrooms, a den and a kitchen. The house opens and closes in a style similar to the buildings in the Medieval Market Village set. This beautifully detailed house would look great with your WWII minifigs and vehicles.')
ww007 = Product.create(product_type_id: instructions.id, name: 'WWII French Store', category_id: military_category.id, subcategory_id: world_war2.id, product_code: 'WW007', price: 1, ready_for_public: false, description: 'This store is modeled after actual buildings in Carentan, France. The destroyed feel is similar to WW002 French Building, and they look good with each other in a WWII layout.')
ww008 = Product.create(product_type_id: instructions.id, name: 'WWII French Corner Bakery', category_id: military_category.id, subcategory_id: world_war2.id, product_code: 'WW008', price: 1, ready_for_public: false, description: 'This WWII French Corner Bakery would be a great addition to your military display. This fits nicely next to our other WWII buildings. The street is littered with debris and the upstairs has been turned upside down. You will get instructions for the building and the French car.')
mw001 = Product.create(product_type_id: instructions.id, name: 'Oshkosh M-ATV', category_id: military_category.id, subcategory_id: modern_warfare.id, product_code: 'MW001', price: 1, ready_for_public: false, description: 'This modern military vehicle is a MRAP (Mine Resistant Ambush Protected) vehicle. It features a hood that tilts forward to reveal the engine. All 4 doors open and close. The top of the cab comes off for easy placement of figures. There is a MG turret up top for your minifigs to protect the convoy.')
mw002 = Product.create(product_type_id: instructions.id, name: 'Jungle Outpost', category_id: military_category.id, subcategory_id: modern_warfare.id, product_code: 'MW002', price: 1, ready_for_public: false, description: 'This jungle outpost with watch tower and communications shack would be great for display with your figures. The ATV goes great with the jungle scene.')
mw003 = Product.create(product_type_id: instructions.id, name: 'Insurgent Stronghold', category_id: military_category.id, subcategory_id: modern_warfare.id, product_code: 'MW003', price: 1, ready_for_public: false, description: 'This insurgent stronghold would look perfect for any modern conflict display. Includes instructions for two damaged buildings and a shot-up technical with machine gun.')
mw004 = Product.create(product_type_id: instructions.id, name: 'NYC Ruins', category_id: military_category.id, subcategory_id: modern_warfare.id, product_code: 'MW004', price: 1, ready_for_public: false, description: 'This New York City ruins playset was modeled after ruins in the Modern Warfare game. The damaged road, building and smashed taxi make for a great display for your soldiers.')

# Castle
ca001 = Product.create(product_type_id: instructions.id, name: 'Medieval Farm House', category_id: other_category.id, subcategory_id: castle.id, product_code: 'CA001', price: 5, ready_for_public: false, tweet: 'Build up your peasant village with this detailed farm house.', description: "It wasn't all castles and battering rams back in the middle ages. Members of the merchant class needed somewhere to live, and this house is the perfect place for the merchant who wants to also keep a small farm. Building and farmyard are situated on a 32x32 baseplate. This is a modular build that features a garden, animal pen, vegetable cart, furniture and a chimney with a fireplace with a hanging pot.")

# Mini/Micro
mm001 = Product.create(product_type_id: instructions.id, name: 'Mini Emergency Vehicles', category_id: other_category.id, subcategory_id: mini_micro.id, product_code: 'MM001', price: 1, ready_for_public: false, description: 'These cute little emergency vehicles are built for fun. They are a smaller scale than minifig scale. You can build a mini fire truck, mini ambulance and mini police SWAT van.')
mm002 = Product.create(product_type_id: instructions.id, name: 'Mini National Bank', category_id: other_category.id, subcategory_id: mini_micro.id, product_code: 'MM002', price: 1, ready_for_public: false, description: "This is a mini version of our minifig-scale CB009 National Bank. It was built to the same scale as Lego's mini modulars. It looks great next to the official models, and next to MM003 Mini Chilis, MM004 Mini Colonial Revival and Bakery and MM005 Mini Precinct.")
mm003 = Product.create(product_type_id: instructions.id, name: "Mini Chili's Restaurant", category_id: other_category.id, subcategory_id: mini_micro.id, product_code: 'MM003', price: 1, ready_for_public: false, description: "This is a mini version of our minifig-scale CB011 Chili's Restaurant. It was built to the same scale as Lego's mini modulars. It looks great next to the official models, and next to MM002 Mini National Bank, MM004 Mini Colonial Revival and Bakery and MM005 Mini Precinct.")
mm004 = Product.create(product_type_id: instructions.id, name: 'Mini Colonial Revival and Bakery', category_id: other_category.id, subcategory_id: mini_micro.id, product_code: 'MM004', price: 1, ready_for_public: false, description: "This is a mini version of our minifig-scale CB002 Colonial Revival and CB010 Bakery. It was built to the same scale as Lego's mini modulars. It looks great next to the official models, and next to MM002 Mini National Bank, MM003 Mini Chilis and MM005 Mini Precinct.")
mm005 = Product.create(product_type_id: instructions.id, name: 'Mini Precinct', category_id: other_category.id, subcategory_id: mini_micro.id, product_code: 'MM005', price: 1, ready_for_public: false, description: "This is a mini version of our minifig-scale CB001 Precinct. It was built to the same scale as Lego's mini modulars. It looks great next to the official models, and next to MM002 Mini National Bank, MM003 Mini Chilis and MM004 Mini Colonial Revival and Bakery.")
mm006 = Product.create(product_type_id: instructions.id, name: 'Lincoln Memorial', category_id: other_category.id, subcategory_id: mini_micro.id, product_code: 'MM006', price: 1, ready_for_public: false, description: "This is our first architectural-style model. It's a great little scale representation of one of America's most famous landmarks. It will look great on your desk, and will be sure to be a conversation-starter.")
mm007 = Product.create(product_type_id: instructions.id, name: 'BCD Mini Modulars', category_id: other_category.id, subcategory_id: mini_micro.id, product_code: 'MM007', price: 1, ready_for_public: false, description: "These models are mini version of our minifig-scale CB009 National Bank, CB011 Chili's Restaurant, CB002 Colonial Revival, CB010 Bakery and CB001 Precinct. They were built to the same scale as Lego's mini modulars. They look great next to each other and with the official mini modulars. They connect to each other in the same way the official mini modulars do.")

# Add Admins
Radmin.create(email: 'lylesjt@gmail.com', password: 'password', password_confirmation: 'password')
Radmin.create(email: 'lylesbk@yahoo.com', password: 'password', password_confirmation: 'password')

# Add Switches
Switch.create(switch: 'maintenance_mode')

if Rails.env.development?
  # Add Users
  user1 = User.create(email: 'lylesjt@yahoo.com', password: 'password', password_confirmation: 'password', tos_accepted: true)
  user2 = User.create(email: 'crazyjulio@juno.com', password: 'password', password_confirmation: 'password', tos_accepted: true)
  user3 = User.create(email: 'lylesbk@yahoo.com', password: 'password', password_confirmation: 'password', tos_accepted: true)

  # Add Orders
  Order.create(user_id: 1, request_id: '09124819284019284901284901281928341902382', transaction_id: '9283492834902893829384209384902384', status: 'COMPLETED')
  Order.create(user_id: 1, request_id: '49324809238409238409238409238439839839933', transaction_id: '2342342342542323330000230023020302', status: 'COMPLETED')
  Order.create(user_id: 3, request_id: '12345678900987654321123123123123123123123', transaction_id: '1234321123456763512328137812787277', status: 'COMPLETED')
  Order.create(user_id: 3, request_id: '12345678900987654321123123123123123123128', transaction_id: '1234321123456763512328137812787278', status: 'INVALID')

  # Add Line Items for Orders
  LineItem.create(order_id: 1, product_id: cv001.id, quantity: 1, total_price: cv001.price)
  LineItem.create(order_id: 1, product_id: cb002.id, quantity: 1, total_price: cb002.price)
  LineItem.create(order_id: 2, product_id: cv011.id, quantity: 1, total_price: cv011.price)
  LineItem.create(order_id: 3, product_id: cv001.id, quantity: 1, total_price: cv001.price)
  LineItem.create(order_id: 4, product_id: cv005.id, quantity: 1, total_price: cv005.price)
  LineItem.create(order_id: 4, product_id: cv011.id, quantity: 1, total_price: cv011.price)

  # Add some news
  Update.create(title: 'This news piece should not be seen on the main page', body: "If this is seen on the main page, it's because of an error! I'm setting up the index page to only show the 3 most recent news items. It may not always stay that way, but that's how I'm setting it up initially. This should only be viewable on the admin news editing side.", image_align: 'float_left', created_at: Date.today - 4)
  Update.create(title: 'Brick City Depot at BrickFair!', body: 'Brick City Depot is going to BrickFair in August! We hope to see you there. Stop by our table and check out our display, and maybe pick up some ready-to-assemble kits. Who knows, we might even give away some free stuff, maybe. Maybe.', image_align: 'top', created_at: Time.now.strftime('%Y-%m-%d %H:%M'))
  Update.create(title: 'Best Sellers', body: "Check out these best sellers. Colonial Revival and Rollback Tow Truck have been consistently our hottest sellers in the City Buildings and Vehicles categories respectively. If you haven't purchased these instructions yet, what are you waiting for? Enjoy!", image_align: 'float_left', created_at: Date.today - 1)
  Update.create(title: 'Announcing the NYC Brownstones', body: "Check it out, fans of New York City architecture and Lego. Just now available is this new line of 3 different styles of brownstone architecture that will fit right in with your city. Don't have a city going yet? Get started now, and enjoy building these 3 classic examples of Gotham City architecture.", image_align: 'float_left', created_at: Date.today - 2)

  # Need a partner for an advertising campaign
  Partner.create(name: 'Roger', url: 'https://www.roger.com', contact: 'roger@roger.com')

  # Need something for testing marketing emails
  AdvertisingCampaign.create(partner_id: 1, reference_code: '0123456789', campaign_live: true, description: 'Not much to say')

  # Need something for testing email campaigns.
  # To get an image for the email, go update this campaign in the interface.
  EmailCampaign.create(description: 'An email campaign', click_throughs: 0, emails_sent: 0, message: 'Buy our stuff', subject: 'Remember us?', guid: '123abc', redirect_link: 'http://google.com')
end
